import 'package:get/get.dart';
import 'package:liqui_app/global/constants/app_constants.dart';

class AppStrings extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_IND': {
          "liqui_money": "LiquiMoney",
          "something_went_wrong": "Something went wrong, Please try again",
          "no_internet_message":
              "No internet found. Please check internet connection & try again",
          "request_timeout_message":
              "Low internet bandwidth, Please check your internet connection",
          "cancel": "Cancel",
          "done": "Done",
          "choose_language": "Choose Language",
          "confirm": "Confirm",
          "welcome": "Welcome",
          "earn_upto_return": "Earn upto 10.5%* returns",
          "try_again_after": "Please try again after",
          "seconds": "secs",
          "by_continue_accept": "By continuing you agree to accept the",
          "terms_conditions": "Terms and Conditions",
          "and": "and",
          "privacy_policy": "Privacy Policy",
          "proceed": "Proceed",
          "mobile_number": "Mobile Number",
          "enter_mobile_number": "Enter your mobile number",
          "enter_mobile_number_error": "Please enter a valid mobile number",
          "unauthorized_error": "Session Expired! Please login again",
          "invalid_request_error": "Invalid request",
          "server_internal_error":
              "Looks like the Server is not responding. Please try again after some time",
          "resource_not_found_error": "Resource url not found",
          "good_morning": "Good Morning",
          "good_afternoon": "Good Afternoon",
          "good_evening": "Good Evening",
          "your_kyc_verification_due": "Your KYC verification is due",
          "verify_kyc_start_investing": "Verify your KYC to start investing",
          "verify_kyc": "Verify KYC",
          "current_value": "Current Value",
          "total_portfolio_value": "Total Portfolio Value",
          "withdrawable": "Withdrawable",
          "locked": "Locked",
          "interest_earned": "Interest Earned",
          "accrued_interest": "Accrued Interest",
          "net_withdraw_interest": "Net of Withdrawn Interest",
          "invest_funds": "Invest Funds",
          "withdraw_funds": "Withdraw Funds",
          "start_sip_5000": "Start SIP\nwith ₹5000",
          "last_transaction": "Last Transaction",
          "all_transactions": "All Transactions",
          "what_is_for_you": "What’s in it for you",
          "know_benefits_having_liqui_account":
              "Know the benefits of having a LiquiMoney account",
          "transactions": "Transactions",
          "total": "Total",
          "amount": "Amount",
          "no_transactions_to_display":
              "There are no transactions yet to display",
          "dashboard": "Dashboard",
          "transaction": "Transaction",
          "profile": "Profile",
          "choose_folio": "Choose Folio",
          "no_data_found": "No data found",
          "refresh": "Refresh",
          "invalid_ifa_message":
              "It seems you are registered with LiquiLoans through one of our fintech partners, kindly use the respective partner website / app for any transaction or service request. For any issues/clarification please write to us on investorfirst@liquiloans.com",
          "name": "Name",
          "phone_number": "Phone Number",
          "pan_Number": "Pan Number",
          "email": "Email Id",
          "address": "Address",
          "not_verified": "Not Verified",
          'add_bank': "Add another bank account",
          "add_address": "Add Another Address",
          "address_reach": "Where can we reach you?",
          "choose_address": "Please choose an address for communication",
          'your_address': "Your Address",
          "basic_detail": "Basic Details",
          'my_bank_account': "My Bank Accounts",
          "withdraw_screen": "Withdraw Funds",
          "withdraw": "Withdraw",
          "amount_to_withdraw": "Amount to Withdraw",
          "verify_otp": "OTP Verification",
          "sent_otp_on_mobile":
              "Otp has been sent on your registered email & mobile number",
          "sent_otp_on": "We've sent an OTP on",
          "edit": "Edit",
          "enter_otp": "Enter OTP",
          "not_receive_otp": "Didn't receive OTP?",
          "resend_otp": "RESEND OTP",
          "verify": "Verify",
          "please_fill_up_cells": "Please fill up all the cells properly",
          "mobile_verification_successful": "Mobile Verification Successfully!",
          "bank_account_added_successful": "Bank Account Added Successfully!",
          "fetching_your_info": "Fetching your information",
          "enter_pan_number": "Enter PAN Number",
          "pancard_details_text":
              "We need your PAN card details to create your account",
          "your_name_on_pan": "Your name as on PAN",
          "dob": "Date of Birth",
          "dob_on_pan": "Your DOB as on PAN",
          "continue": "Continue",
          "do_it_later": "Do It Later",
          "account_number": "Account Number",
          "enter_account_number": "Enter your account number",
          "account_holder_name": "Account Holder Name",
          "enter_ifsc_code": "Enter your bank's IFSC",
          "bank_name": "Bank Name",
          "enter_your_pincode": "Enter your pincode",
          "where_can_we_reach_you": "Where can we reach you?",
          "address_line_one": "Address Line 1",
          "address_line_two": "Address Line 2",
          "city": "City",
          "state": "State",
          "submit": "Submit",
          "terms": "Terms",
          "terms_value":
              "Terms of service are the legal agreements between a service provider and a person who wants to use that service. The person must agree to able by the terms of service in order to use the offered. Terms of service can also be merely a disclaimer, especially regarding the use of websites.",
          "conditions": "Conditions",
          "conditions_value": "Violations of system or network security may result in civil or criminal "
              "liability. We will investigate such violations and prosecute users who are involved. "
              "You agree not to use any device, software or routine to interfere or attempt to "
              "interfere with the proper working of this website or any activity being conducted on "
              "Website. You agree, further not to use or attempt to use any engine, software, tool, agent or other device or mechanism including without limitation, browser, spiders, robots, avatars or intelligent agents to navigation or search this website on the search engine and search agents available from us on this Website.",
          "i_accept": "I agree to accept the Terms & Conditions",
          "sign_agreement": "Sign Agreement",
          "please_enter_pan": "Please enter a valid PAN",
          "name_cannot_be_empty": "Name cannot be empty",
          "please_enter_name": "Please enter a valid name",
          "please_enter_dob": "Please enter a valid DOB",
          "enter_six_digit_otp": "Please enter six digit OTP",
          "city_name_cannot_be_empty": "City name cannot be empty",
          "state_name_cannot_be_empty": "State name cannot be empty",
          "account_holder_name_cannot_be_empty":
              "Account Holder name cannot be empty",
          "bank_name_cannot_be_empty": "Bank name cannot be empty",
          "please_enter_address": "Please enter a valid address",
          "please_enter_email": "Please enter a valid email",
          "please_enter_pincode": "Please enter a valid pincode",
          "please_enter_account_number": "Please enter a valid account number",
          "please_enter_ifsc": "Please enter a valid IFSC",
          "enter_email": 'Enter email ID',
          "gender": "Gender",
          "male": 'Male',
          "female": 'Female',
          "liquid": '0 MHP',
          "lock-in": 'Lock-in',
          "lock-in_tenure": 'Lock-In Tenure',
          "amount_to_invest": 'Amount to Invest',
          "months": 'Months',
          "interest_payout": "Interest Payout",
          "interest_earned_year": 'Interest earned per year',
          "interest_earned_pm": 'Interest earned per month',
          "interest_earned_for": "Interest earned for",
          "interest_rate": 'Interest Rate',
          "compare_return": 'Compare Returns',
          "back_to_dashboard": "Go back to dashboard",
          "invest_more": "Invest More",
          "amt_requested": 'Amount Requested',
          "amt_invested": 'Amount Invested',
          "withdrawal_request": "Withdrawal Request",
          "enter_withdrawal_amt": "Enter your withdrawal amount",
          "select_bank": "Select Bank",
          "your_withdrawal_request":
              "Your withdrawal request has been received successfully",
          "congratulations": "Congratulations!",
          "amt_credited_msg":
              "This amount will be credited in 2-3 working days",
          "txn_ref_num": "Txn Reference Number",
          "txn_ref_numNN": "TxN Reference Number",
          "crediting_to": "Crediting to",
          "locking_tenure": "Lock-in Tenure",
          "my_profile": "My Profile",
          "delete": "Delete",
          "make_primary": "Make Primary",
          "withdraw_limit": "Withdrawal Limit",
          "no_camera_available_error": "No camera available",
          "error_message": "Error Message",
          "capture_image": "Capture Image",
          "capture_image_error": "Please capture image",
          "photos_permission_error":
              "We are having problems retrieving permissions. Please allow photos permission from app settings",
          "select_image": "Select Image",
          "grant_permission": "Grant Permission",
          "photos_permissions": "Photos Permissions",
          "permission_error_message":
              "We are having problems retrieving permissions. Please grant required permissions from app settings",
          "back": "Back",
          "alert": "Alert",
          "okay": "Okay",
          "camera_permission_required": "Camera permission required",
          "photo_permission_required": "Photo permission required",
          "storage_permission_required": "Storage permission required",
          "notification_permission_required":
              "Notification permission required",
          "withdraw_to": "Withdraw to",
          "account_details": "Account Details",
          "change_password": "Change Password",
          "signout": "Signout",
          "basic_information": "Basic Information",
          "my_bank_accounts": "My Bank Accounts",
          "my_address": "My Address",
          "investor_id": "Investor ID",
          "try_again": "Try Again",
          "dismiss": "Dismiss",
          "your_bank_accounts": "Your Bank Accounts",
          "your_withdrawal_amt": "Your withdrawable balance is",
          "complete_your_kyc": "Complete your KYC to become investment ready",
          "complete_kyc": "Complete KYC",
          "choose_scheme": "Choose Scheme",
          "invest_now": "Invest Now",
          "rs": "₹",
          "choose_your_folio":
              "Choose the IFA portfolio under which you want to make this investment",
          "choose_your_scheme": "Choose scheme you want to invest in",
          "enter_valid_amount": "Please enter a valid amount",
          "investment_amount": "Investment Amount",
          "investment_type": "Investment Type",
          "available_methods": "Available Methods",
          "upload_now": "Upload Now",
          "add_file": "Add file",
          "invalid_ifa": "Invalid IFA",
          "enter_amount_less_than": "Enter amount less than",
          "scheme_not_selected": "Please select a scheme to proceed",
          "enter_amount_greater_than": "Enter amount greater than",
          "resend_otp_after": "You can resend otp after",
          "cannot_fetch_city": "Cannot fetch city",
          "cannot_fetch_state": "Cannot fetch state",
          "upload_bank_doc": "Upload Bank Document",
          "select_bank_proof": "Select Bank Proof",
          "photo": "Camera",
          "img_upload": "Gallery",
          "upload_doc": "Document",
          "banking": "Banking",
          "select_proof": "Select Proof",
          "upload_proof": "Upload Proof From",
          "upload_pan_doc": "Upload Pan Document",
          "select_proof_identity": "Select Proof of Identity",
          "upload_address_doc": "Upload Address Document",
          "select_proof_address": "Select Proof Of Address",
          "space": " ",
          "no_scheme_available": "No schemes available",
          "growth": "Growth",
          "monthly": "Monthly",
          "select_amount_tenure": "Select proper amount and tenure",
          "comparative_returns":
              "Comparative Returns across top investment tools",
          "if_you_invest": "If you invest",
          "with_liquimoney_it_will": "With Liquimoney, it will become",
          "saving_account": "Saving A/C",
          "fixed_deposit": "Fixed Deposit",
          "tenure_in_months": "Tenure(in months)",
          "saving": "Saving",
          "returns_from_other_tools": "Returns from other tools in market",
          "investment_limit": "Investment Limits",
          "payment_mode": "Payment Mode",
          "verify_mobile": "Verify Mobile",
          "add_bank_account": "Add Bank Account Details",
          "investmentAbove10L":
              '*T&C Apply\nRBI requirement: networth certificate for >10 lakh investments',
          "kyc_under_review": "Your kyc is under review",
          "kyc_updates": "KYC Updates",
          "transaction_details": "Transaction Details",
          "deposit_type": "Deposit Type",
          "lock-in_period": "Lock-in Period",
          "your_transaction_is_sure": "Your transactions are 100% secure",
          "having_issues": "Having issues?",
          "contact_support": "Contact Support",
          "amount_deposited": "Amount Deposited",
          "add_money_ifa_change_confirmation":
              'Are you sure you want to add money to',
          "withdraw_ifa_change_confirmation":
              'Are you sure you want to withdraw money from',
          "add_bank_ifa_change_confirmation":
              'Are you sure you want to add bank account to',
          "delete_bank_account_confirmation":
              'Are you sure you want to delete this bank account?',
          "cancel_transaction_confirmation":
              'Are you sure you want to cancel this transaction?',
          "login": 'Log In',
          "logout": 'Log out',
          "logout_confirmation": 'Are you sure you want to log out?',
          "app_exit_confirmation": 'Are you sure you want to exit the App?',
          'next': 'Next',
          'earn_upto': 'Earn upto 10.5% Returns',
          'crisil_text':
              'Invest in world`s first CRISIL assessed P2P NBFC; licensed and regulated by RBI',
          "transaction_completed": 'Transaction completed successfully',
          "transaction_success": 'Transaction Success',
          "investment_successful": 'Your investment is successful',
          "transaction_failed": 'Oops! Transaction failed',
          "transaction_cancelled": 'Oops! Transaction cancelled',
          "contact_us": 'Contact Us',
          "faq": 'FAQs',
          "refer_friend": 'Refer A Friend',
          "download_app_text":
              'Hey! Come check out LiquiLoans investment app where you can earn upto 10.5% returns! Click this link & download the app now to start investing!',
          "app_update_msg":
              'Update Required\nAn update to LiquiMoney is required to continue',
          "app_store_url":
              'https://apps.apple.com/in/app/liquimoney/id1612622624',
          "play_store_url":
              'https://play.google.com/store/apps/details?id=com.liquimoney',
          "update_now": 'Update Now',
          "update_later": "Update Later",
          "coming_soon": "Coming Soon",
          "deposit": "Deposit",
          "other": "Other",
          "total_credited_amount": "Total Interest Credited to your account",
          "total_invested_amount": "Total Invested Amount",
          "total_withdrawn_amount": "Total Withdrawn Amount",
          "minimum_investment_amount_error":
              "Minimum amount that can be invested is",
          "enter_amount_less_than_scheme_invest":
              "Maximum amount that can be invested in this scheme is",
          "enter_amount_more_than_scheme_invest":
              "Minimum amount that can be invested in this scheme is",
          "fd_saving_interest_terms":
              "*Source : Avg rates are taken by the top banks of India",
          "go_back": "Go Back",
          "credited": "Credited",
          "debited": "Debited",
          "monthly_interest_repayment": 'Monthly Interest Repayment',
          "liquid_investment": "0 MHP Investment",
          "term_investment": "Term Investment",
          "withdraw_anytime": "Withdraw anytime",
          "withdraw_specific_tenure": "Withdraw after specific tenure",
          "unable_to_load_image": "Unable to load image",
          "unable_to_load_document": "Unable to load document",
          "annualized_returns": "Annualized Returns",
          "please_add_bank_details":
              "Please add bank details to withdraw money",
          "device_lock_issue":
              "There seems to be problem with device lock.\nEnable device or biometric lock in phone settings",
          "verify_identity": "Verify Identity",
          "verify_security_msg":
              "For your security kindly verify your identity",
          "enable_app_lock": "Enable App Lock",
          "screen_lock_enabled": "Screen Lock Enabled",
          "error_authenticating": "Error Authenticating",
          "lock_hint_text":
              "Unlock your Screen with PIN, pattern, password, face,or fingerprint",
          "unlock_app": "Unlock LiquiMoney",
          "unlock": "Unlock",
          "change_theme": "Change Theme",
          "choose_how_app_theme_experience_looks":
              "Choose how your LiquiMoney experience looks for this device.",
          "app_device_mode_theme_description":
              "If you choose Device settings, this app will use the mode that's already selected in the device settings.",
          "device_settings": "Device settings",
          "dark_mode": "Dark mode",
          "light_mode": "Light mode",
          "referral_url_error": "Error fetching referral code",
          "investment_details": "Investment Details",
          "portfolio": "Portfolio",
          "invested_amount": "Invested Amount",
          "redeemed_interest": "Redeemed Interest",
          "capitalised_interest": "Capitalised Interest",
          "add_money": "+ Money",
          "invested": "Invested",
          "net_principal_amount": "Net Principal Amount",
          "skip": 'SKIP',
          "your_portfolio_value":
              "It's your total portfolio value (Principle + Accrued interest) across all IFA folios",
          "withdrawable_value": "Withdrawable value",
          "your_withdrawable_value":
              "It's your withdrawable value which you can withdraw anytime without any exit load",
          "locked_value": "Locked value",
          "your_locked_value":
              "It's your locked in value which you can withdraw after completion of applicable lockin period",
          "Accrued_value": "Accrued Interest value",
          "your_Accrued_value": "Net accrued interest value",
          "select_folio": "Select Folio",
          "select_your_folio":
              "Select the IFA name here to see IFA wise portfolio details",
          "add_money_investment":
              "Click here to Add money to your investment portfolio",
          "your_investor_id": "Your investor unique id",
          "enter_amount_to_withdraw": "Enter amount which you want to withdraw",
          "withdraw_to_bank": "Withdraw to bank",
          "select_bank_to_withdraw":
              "Select the bank to which you want the payout to be made",
          "profile_details": "Profile Details",
          "your_profile_details":
              "You basic profile details, bank details and address details",
          "select_payout_type": "Select payout type",
          "select_payout_investment":
              "Select the payout type for your investment",
          "enter_investment_amount": "Enter the investment amount",
          "select_scheme_type": "Select scheme type",
          "select_type_of_investment":
              "Select type of scheme in which you want to invest your funds in",
          "selected_interest_earned":
              "Interest earned for selected scheme based on entered investment amount.",
          "annualized_selected_returns":
              "Annualized returns for the selected scheme",
          "choose_folio_from_here": "Choose folio form here",
          "returns_with_fd":
              "Comparative analysis of your projected returns vis-a-vis Fixed Deposit and Saving account",
          "investment_tenure": "Select you investment tenure",
          "its_all_investment":
              "List of all your investment, withdrawal and interest payout transactions",
          "investment_transaction": "Investment transactions",
          "all_investment_transaction":
              "List of all your investment transactions",
          "interest_transaction": "Interest transactions",
          "all_interest_transaction":
              "List of all your interest paid out transactions",
          "withdraw_transaction": "Withdraw transactions",
          "all_withdraw_transaction":
              "List of all your withdrawal transactions",
          "close": "Close",
          "enable_disable_app_lock": "Enable/Disable app lock",
          "put_app_security_for_app_lock": "You can put app security",
          "prev": "Prev",
          "on_finish_show_case": "onFinish",
          "on_click_target_show_case": "onClickTarget",
          "on_skip_show_case": "onSkip",
          "drop_down_invest_fund": "drop_down_invest_fund",
          "drop_down_withdraw_fund": "drop_down_withdraw_fund",
          "button_my_bank_account": "button_my_bank_account",
          "drop_down_my_bank_account": "drop_down_my_bank_account",
          "losing_text": "OH NO!\nYou are losing $rupeeSymbol",
          "why_lose_when_you_can_earn": "Why lose when you can earn!",
          "current_value_aod": "Value as on Date:",
          "on": "On",
          "off": "Off",
          "choose_folio_subtext_create_account":
              "You can access your investments made on other platforms too. Please choose a folio to continue or create a Liquiloans account.",
          "choose_folio_subtext_continue": "Please choose a folio to continue.",
          "create_new_liquiloans_account": "Create New Liquiloans Account",
          "or": "OR",
          "your_kyc_verification_failed": "Your KYC Verification has failed",
          "sorry_kyc_verification_failed":
              "Sorry but your KYC verification has failed because",
          "retry": "Retry",
          "please_try_again": "please try again",
          "my_portfolio": "My Portfolio",
          "total_current_value": "Total Current Value",
          "principal_investment": "Principal Investment",
          "maturing_on": "Maturing on",
          "amount_withdrawn": "Amount Withdrawn",
          "total_interest": "Total Interest",
          "total_investment": "Total Investment",
          "scheme_switch": "Scheme Switch",
          "reinvestment": "Reinvestment",
          "investment": "Invested",
          "investments": "Investments",
          "passbook": "Passbook",
          "download": "Download",
          "download_passbook": "Download Passbook",
          "choose_the_date_range":
              "Choose the date range to download the passbook",
          "start_date": "Start Date",
          "end_date": "End Date",
          "select_end_date": "Select end date",
          "select_start_date": "Select start date",
          "end_date_should_be_greater":
              "End date should be greater than start date",
          "add_address_for_communication":
              "Please add an address for communication",
          "please_download_passbook":
              "Please download passbook for more details",
          "pure_lock_in": "Pure Lock-in",
          "flexi_lock_in": "Flexi Lock-in",
          "active_schemes": "Active Schemes",
          "active_transactions": "Active Transactions",
          "withdrawal_breakup": "Withdrawal BreakUp",
          "principal": "Principal",
          "interest": "Interest",
          "utr_no": "UTR No.",
          "retry_payment": "Retry Payment",
          "processing_transcation": "Processing Transcation",
          "transaction_failedd": "Transaction Failed",
          "please_wait": "Please wait..",
          "thank_you_for_your_patience": "THANK-YOU FOR YOUR PATIENCE",
          "oh_snap_payment_failed": "Oh Snap.. Payment Failed!",
          "continue_payment": "Continue Payment",
          "are_you_sure": "Are you sure?",
          "you_are_losing_out_on": "You are losing out on",
          "your_investment_was_unsuccessful":
              "Your investment was unsuccessful",
          "we_re_securely_processing_your_payment":
              "We're securely processing\nyour payment",
          'rbi_guide_line':
              'With respect to the recent (dated 16th August 2024) revision to Master Direction - Non-Banking Financial Company – Peer to Peer Lending Platform (Reserve Bank) Directions, 2017 - certain functionalities on the platform may be disabled temporarily. Please reach out to your Relationship Manager/ Financial Advisor for more details.'
        }
      };
}
